"""Generate docs/PREAMBLE_CATALOG.md from src/preamble_library.py."""

from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = PROJECT_ROOT / "src"
DOCS_DIR = PROJECT_ROOT / "docs"
OUTPUT_FILE = DOCS_DIR / "PREAMBLE_CATALOG.md"

sys.path.insert(0, str(SRC_DIR))

from preamble_library import PREAMBLE_LIBRARY  # noqa: E402

CATEGORY_ORDER = [
    "Consumer",
    "Producer",
    "Risk",
    "Dynamic",
    "Optimization",
    "Welfare",
    "GameTheory",
    "Macro",
]


def _lean_file_link(lean_path: Path) -> str:
    """Return a markdown link target relative to docs/."""
    repo_relative = lean_path.relative_to(PROJECT_ROOT)
    return (Path("..") / repo_relative).as_posix()


def build_catalog_markdown() -> str:
    """Render the preamble catalog as grouped markdown tables."""
    entries_by_category: dict[str, list] = {name: [] for name in CATEGORY_ORDER}
    for entry in PREAMBLE_LIBRARY.values():
        parts = entry.lean_module.split(".")
        category = parts[2] if len(parts) > 2 else "Other"
        entries_by_category.setdefault(category, []).append(entry)

    lines: list[str] = [
        "# LeanEcon Preamble Catalog",
        "",
        "Generated by `scripts/generate_preamble_catalog.py` from `src/preamble_library.py`.",
        "",
        (
            "These names are the values accepted by `preamble_names` in "
            "`POST /api/v1/formalize`, and they may also appear in classifier "
            "`preamble_matches`."
        ),
        "",
        (
            f"LeanEcon currently ships {len(PREAMBLE_LIBRARY)} reusable preamble "
            "entries grouped below by domain."
        ),
        "",
    ]

    for category in CATEGORY_ORDER:
        entries = sorted(entries_by_category.get(category, []), key=lambda entry: entry.name)
        if not entries:
            continue

        lines.extend(
            [
                f"## {category}",
                "",
                "| Name | Lean Module | Lean File | Description | Parameters | Keywords |",
                "| --- | --- | --- | --- | --- | --- |",
            ]
        )
        for entry in entries:
            parameters = ", ".join(entry.parameters) if entry.parameters else "(none)"
            keywords = ", ".join(entry.keywords)
            lean_file = entry.lean_path.relative_to(PROJECT_ROOT).as_posix()
            link = _lean_file_link(entry.lean_path)
            lines.append(
                f"| `{entry.name}` | `{entry.lean_module}` | [{lean_file}]({link}) | "
                f"{entry.description} | `{parameters}` | {keywords} |"
            )
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    OUTPUT_FILE.write_text(build_catalog_markdown() + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT_FILE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
